-- function SCR_EVENT_TODAY_NUMBER_DROPITEM(self, sObj, msg, argObj, argStr, argNum)  
--     local aObj = GetAccountObj(self)
--     local TeamLevel = GetTeamLevel(self);

--     if TeamLevel < 2 or aObj.EV180109_STEAM_BEGINNER_JOIN_CHECK ~= 0 then
--         return
--     end
--     if (argObj.ClassID >= 45132 and argObj.ClassID <= 45136) or (argObj.ClassID >= 45110 and argObj.ClassID <= 45111) then
--         local rand = IMCRandom(1, 5)        
--         if rand == 5 then
--             local tx = TxBegin(self);
-- 			TxGiveItem(tx, 'Event_Number_Ticket', 1, "EV180109_SETTLE_TICKET_GIVE");
-- 			local ret = TxCommit(tx);
--         end
--     end
-- end

-- function SCR_STEAM_SETTLE_EVENT_DIALOG(self,pc)
--     local aObj = GetAccountObj(pc)
--     local TeamLevel = GetTeamLevel(pc);
--     local qCount = GetInvItemCount(pc, 'Event_Number_Ticket')
--     local now_time = os.date('*t')
--     local yday = now_time['yday']

--     if TeamLevel < 2 or aObj.EV180109_STEAM_BEGINNER_JOIN_CHECK ~= 0 then
--         ShowOkDlg(pc,'EVENT_STEAM_SETTLE_DLG_1', 1)
--         return
--     end
    
--     local reward = {
--     {1, 'Drug_Fortunecookie_14d', 1},{2, 'Event_drug_steam_1h', 1},
--     {3, 'Event_Goddess_Statue_3d', 1},{4, 'Drug_Fortunecookie_14d', 1},
--     {5, 'Mic', 1},{6, 'Adventure_Reward_Seed_3d', 1},
--     {7, 'Premium_dungeoncount_Event', 1},{8, 'Drug_Fortunecookie_14d', 1},
--     {9, 'Event_Steam_Happy_New_Year', 1},{10, 'RestartCristal', 1},
--     {11, 'GIMMICK_Drug_HPSP2', 1},{12, 'Drug_Fortunecookie_14d', 1},
--     {13, 'Premium_indunReset_1add_14d', 1},{14, 'Premium_awakeningStone14', 1},
--     {15, 'Premium_WarpScroll_14d', 1},{16, 'Drug_Fortunecookie_14d', 1},
--     {17, 'Premium_boostToken_14d', 1},{18, 'Moru_Silver', 1},
--     {19, 'Moru_Gold_14d', 1},{20, 'Premium_Enchantchip14', 1},
--     {21, 'Ability_Point_Stone_500_14d', 1}
--     }

--     if aObj.EV180109_STEAM_SETTLE_COUNT >= 28 then -- EV170711_TODAY_NUMBER_3
--         ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_6', 1)
--         return     
--     elseif aObj.EV180109_STEAM_SETTLE_DAY_CHECK == yday then -- EV170711_TODAY_NUMBER_2
--         ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_5', 1)
--         return         
--     elseif qCount < 1 then
--         ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_4', 1)
--         return
--     elseif qCount >= 1 then
-- --print(aObj.EV180109_STEAM_SETTLE_RAND_REWARD) 
--         if aObj.EV180109_STEAM_SETTLE_RAND_REWARD == 0 then -- EV170711_TODAY_NUMBER_1
--             local rand = IMCRandom(1, 10)
--             local tx = TxBegin(pc)
--             TxSetIESProp(tx, aObj, 'EV180109_STEAM_SETTLE_RAND_REWARD', rand)
--             local ret = TxCommit(tx)
-- --print(aObj.EV180109_STEAM_SETTLE_RAND_REWARD)
--         end
--     end
--         local inputSelect = ShowTextInputDlg(pc, 0, 'EV_NUMBER_SEL1')
--         local input = tonumber(inputSelect)
--         if input ~= nil and tonumber(input) > 0 and tonumber(input) < 11 then
--             local tx = TxBegin(pc)
--             TxTakeItem(tx, 'Event_Number_Ticket', 1, 'EV180109_SETTLE_TICKET_TAKE');
--             local ret = TxCommit(tx)
--             if ret == "SUCCESS" and tonumber(input) == aObj.EV180109_STEAM_SETTLE_RAND_REWARD then
--                 for i = 1, table.getn(reward) do
--                     if reward[i][1] == aObj.EV180109_STEAM_SETTLE_COUNT + 1 then
--                         local result = i
--                         local tx = TxBegin(pc)
--                         TxSetIESProp(tx, aObj, 'EV180109_STEAM_SETTL_JOIN_CHECK', 1)
--                         TxSetIESProp(tx, aObj, 'EV180109_STEAM_SETTLE_RAND_REWARD', 0)
--                         TxSetIESProp(tx, aObj, 'EV180109_STEAM_SETTLE_DAY_CHECK', yday)
--                         TxSetIESProp(tx, aObj, 'EV180109_STEAM_SETTLE_COUNT', aObj.EV180109_STEAM_SETTLE_COUNT + 1)
--                             for j = 2, #reward[result], 2 do
--                                 TxGiveItem(tx, reward[result][j], reward[result][j+1], 'EV180109_SETTLE_REWARD');
--                             end
--                         local ret = TxCommit(tx)
--                         ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_2', 1)
--                         break
--                     end
--                 end
--             elseif ret == "SUCCESS" and tonumber(input) ~= aObj.EV180109_STEAM_SETTLE_RAND_REWARD then
--                 ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_1', 1)
--             end
--         else
--             ShowOkDlg(pc, 'NPC_EVENT_TODAY_NUMBER_3', 1)
--         end
-- end

-- function SCR_STEAM_EVENT_TODAY_TICKET(self,argObj,BuffName,arg1,arg2)

--     local select = ShowSelDlg(self, 0, 'EVENT_STEAM_TODAY_TICKET_DLG_1', ScpArgMsg("Event_Steam_YC_2"), ScpArgMsg("Event_Steam_YC_3"), ScpArgMsg("Event_Steam_YC_4"), ScpArgMsg("Cancel"))

--     if select == 1 then
--         MoveZone(self, 'c_Klaipe', -179, 150, 72);
--         AddBuff(self, self, 'Drug_Haste', arg1, 0, arg2, 1);
--     elseif select == 2 then
--         MoveZone(self, 'c_orsha', 145, 177, 278);
--         AddBuff(self, self, 'Drug_Haste', arg1, 0, arg2, 1);
--     elseif select == 3 then
--         MoveZone(self, 'c_fedimian', -243, 161, -303);
--         AddBuff(self, self, 'Drug_Haste', arg1, 0, arg2, 1);
--     end
-- end