function SCR_SSN_MASTER_HUNTER1_3_BASIC_HOOK(self, sObj)
	SCR_REGISTER_QUEST_PROP_HOOK(self, sObj)
end

function SCR_CREATE_SSN_MASTER_HUNTER1_3(self, sObj)
	SCR_SSN_MASTER_HUNTER1_3_BASIC_HOOK(self, sObj)
end

function SCR_REENTER_SSN_MASTER_HUNTER1_3(self, sObj)
	SCR_SSN_MASTER_HUNTER1_3_BASIC_HOOK(self, sObj)
	ABANDON_TRACK_QUEST(self, sObj.QuestName, 'SYSTEMCANCEL', 'PROGRESS')
end

function SCR_DESTROY_SSN_MASTER_HUNTER1_3(self, sObj)
end