function SCR_SSN_MASTER_ROGUE1_BASIC_HOOK(self, sObj)
end

function SCR_CREATE_SSN_MASTER_ROGUE1(self, sObj)
	SCR_SSN_MASTER_ROGUE1_BASIC_HOOK(self, sObj)
end

function SCR_REENTER_SSN_MASTER_ROGUE1(self, sObj)
	SCR_SSN_MASTER_ROGUE1_BASIC_HOOK(self, sObj)
end

function SCR_DESTROY_SSN_MASTER_ROGUE1(self, sObj)
end