function SCR_SSN_SUBMASTER_LINKER1_2_BASIC_HOOK(self, sObj)
end

function SCR_CREATE_SSN_SUBMASTER_LINKER1_2(self, sObj)
	SCR_SSN_SUBMASTER_LINKER1_2_BASIC_HOOK(self, sObj)
end

function SCR_REENTER_SSN_SUBMASTER_LINKER1_2(self, sObj)
	SCR_SSN_SUBMASTER_LINKER1_2_BASIC_HOOK(self, sObj)
	ABANDON_TRACK_QUEST(self, sObj.QuestName, 'SYSTEMCANCEL', 'PROGRESS')
end

function SCR_DESTROY_SSN_SUBMASTER_LINKER1_2(self, sObj)
end