function MINIMIZED_HOUSING_PROMOTE_BOARD_ON_INIT(addon, frame)
	addon:RegisterMsg("GAME_START", "MINIMIZED_HOUDING_PROMOTE_BOARD_BUTTON_OPEN_CHECK");
end

function MINIMIZED_HOUDING_PROMOTE_BOARD_BUTTON_OPEN_CHECK(frame)
    frame:ShowWindow(0);
end