function ANCIENT_MON_LIST_ON_INIT(addon, frame)
--    addon:RegisterMsg('ANCIENT_MON_REGISTER', 'ON_ANCIENT_MON_REGISTER');
--    addon:RegisterMsg('ANCIENT_MON_REMOVE', 'ON_ANCIENT_MON_REMOVE');
--    addon:RegisterMsg('ANCIENT_MON_LIST_LOAD', 'ON_ANCIENT_MON_LIST_LOAD');
--    addon:RegisterMsg('ANCIENT_MON_UPDATE_EXP', 'ON_ANCIENT_MON_UPDATE');
--    addon:RegisterMsg('ANCIENT_MON_COMPOSE', 'ON_ANCIENT_MON_UPDATE');
--    addon:RegisterMsg('ANCIENT_MON_UPDATE_SLOT', 'ON_ANCIENT_MON_UPDATE');
end